version: '3'

services:

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker --beat --loglevel=INFO
    depends_on:
      - redis
      - app
