# Generated by Django 4.2.7 on 2024-03-12 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место выполнения привычки')),
                ('time', models.TimeField(verbose_name='Время, когда необходимо выполнять привычку')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('sign_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('periodicity', models.IntegerField(choices=[(1, 'раз в день'), (2, 'раз в два дня'), (3, 'раз в три дня'), (4, 'раз в четыре дня'), (5, 'раз в пять дней'), (6, 'раз в шесть дней'), (7, 'раз в семь дней')], verbose_name='Периодичность выполнения привычки')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('time_complete', models.TimeField(verbose_name='Время на выполнение привычки')),
                ('sign_publicity', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('id',),
            },
        ),
    ]
