# Generated by Django 4.2.7 on 2024-03-17 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='action_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 17, 20, 40, 10, 864277), verbose_name='Дата действия'),
        ),
    ]
