# Generated by Django 4.2.7 on 2024-03-17 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action_date',
            field=models.DateField(default=datetime.date(2024, 3, 17), verbose_name='Дата действия'),
        ),
    ]
